version: '3.8'

services:

  db:
    image: neo4j:5.16.0-community-bullseye
    restart: always
    # environment:
    #   NEO4J_AUTH : neo4j/password #none
    volumes:
      - ./neo4j:/data
    ports:
      - 7687:7687
      - 7474:7474
    expose:
      - 7687
      - 7474
    networks:
      - backend_network
    
  backend:
    build:
      context: ./codeBase
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - 5001:5001
    networks:
      - backend_network
    depends_on:
      - db
    expose:
      - 5001

# volumes:
#   neo4j:

networks:
  backend_network: